openfda:
  url: https://api.fda.gov
  enable-cache: true
  cron-expression-for-cache-eviction: "0 0 * * * *"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always