feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    "com.barthand": debug

openfda:
  enable-cache: false
  cron-expression-for-cache-eviction: "*/30 * * * * *"
